"""Signed imgproxy URLs. No thumbnail is ever generated by this service
and no resized copy is ever stored -- imgproxy resizes on request, from
the original in S3, and the signature is the only thing stopping a client
from asking it to fetch and transform an arbitrary URL on someone else's
behalf.
"""

from __future__ import annotations

import base64
import hashlib
import hmac

from django.conf import settings

# rs:fill crops to exactly the target box (a thumbnail grid cell);
# rs:fit letterboxes instead, which is wrong for a grid and right for a
# single enlarged view. g:sm asks imgproxy's smart-crop for fill so a
# 16:9 source cropped to a square doesn't reliably cut off the subject.
PRESETS = {
    "thumb": "rs:fill:320:320:0/g:sm",
    "preview": "rs:fit:1600:1600:0",
}


def _sign(path: str) -> str:
    key = bytes.fromhex(settings.IMGPROXY_KEY)
    salt = bytes.fromhex(settings.IMGPROXY_SALT)
    digest = hmac.new(key, salt + path.encode(), hashlib.sha256).digest()
    # Standard base64 uses + and / -- both legal in a URL path segment
    # only after percent-encoding, which imgproxy's own clients don't do
    # for you. url-safe base64 sidesteps the question instead of relying
    # on every caller remembering to encode it.
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode()


def signed_url(source_url: str, preset: str) -> str:
    encoded_source = base64.urlsafe_b64encode(source_url.encode()).rstrip(b"=").decode()
    path = f"/{PRESETS[preset]}/{encoded_source}"
    signature = _sign(path)
    return f"{settings.IMGPROXY_BASE_URL}/{signature}{path}"


def variants(s3_key: str) -> dict[str, str]:
    source = f"s3://{settings.AWS_STORAGE_BUCKET_NAME}/{s3_key}"
    return {preset: signed_url(source, preset) for preset in PRESETS}
